spring:
  h2:
    console:
      enabled: true
      path: /h2

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassNam: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
